#!/usr/bin/env python3

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure

assert version_info.major == 2

options = cli()

f = [get_filter(from_string='Averaged contributions',
                      num_lines=5,
                      rel_tolerance=1.0e-4)
          ]

ierr = run(options,
           configure,
           input_files=['gimic.inp'],
           filters={'stdout': f})

sys.exit(ierr)